const express = require('express')
const jwt = require('jsonwebtoken')
const app = express()

app.use(express.json);

//decode, verify and generating a jwrt

//JWT generation

const value = {
    name: "Chaitanya",
    accountNumber: 777777
}

const token = jwt.sign(value, 'secret');

//using the jwt generated by the other program with different signature throws error of invalid signataure, this is exactly what this will throw as the strign we are verifying is a jwt generated for the same content but a different signature
try{
    const verified = jwt.verify("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hhaXRhbnlhIiwiYWNjb3VudE51bWJlciI6Nzc3Nzc3LCJpYXQiOjE3MTMyNjc0NzF9.i7lsvf8H6S0u1vAaoSHOVcCY31xaOPPFjYlfjsoGBLU", "secret");
    console.log(verified);
} 
catch(e){
    console.log(e);
}

 // this throes error: invalid signature


// But this verrification will give me the content values of the jwt back because this is the token we generated for those values using this signature
const verification = jwt.verify("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2hhaXRhbnlhIiwiYWNjb3VudE51bWJlciI6Nzc3Nzc3LCJpYXQiOjE3MTMyNjY3MjV9.2gduHZIrYjbreKCAfB_zaelSRFP5-sm4eMciHsLOB4c", "secret");
console.log(verification);


console.log(token);
app.listen(3000);